import type { Trip } from "@pangofold/shared";

export const MOCK_TRIP: Trip = {
  id: "mock-trip-1",
  title: "Montreal & Quebec City Summer 2026",
  coverImageUrl: undefined,
  startDate: "2026-07-10",
  endDate: "2026-07-17",
  sourceDocUrl: "https://docs.google.com/document/d/mock",
  ownerId: "mock-user",
  shareSlug: "a1b2c3d4",
  createdAt: "2026-04-09T00:00:00Z",
  destinations: [
    {
      id: "dest-1",
      name: "Montreal",
      duration: "4 nights",
      hotel: {
        name: "Hotel Nelligan",
        address: "106 Rue Saint-Paul O, Montréal",
        link: "https://hotelnelligan.com",
      },
      sortOrder: 0,
      days: [
        {
          id: "day-1",
          dayNumber: 1,
          date: "2026-07-10",
          items: [
            {
              id: "item-1",
              time: "9:00 AM",
              title: "Arrive at YUL, Uber to hotel",
              category: "transport",
              location: "Montréal–Trudeau Airport",
              cost: "$45",
              isChecked: false,
              sortOrder: 0,
            },
            {
              id: "item-2",
              time: "11:00 AM",
              title: "Walk through Old Montreal",
              description: "Cobblestone streets, Notre-Dame Basilica, waterfront",
              category: "activity",
              location: "Vieux-Montréal",
              isChecked: false,
              sortOrder: 1,
            },
            {
              id: "item-3",
              time: "1:00 PM",
              title: "Lunch at Schwartz's Deli",
              description: "Famous smoked meat sandwich - get the medium fat",
              category: "food",
              location: "3895 Boul Saint-Laurent",
              link: "https://www.schwartzsdeli.com",
              cost: "$15",
              isChecked: false,
              sortOrder: 2,
            },
            {
              id: "item-4",
              time: "3:00 PM",
              title: "Mount Royal hike",
              description: "Take the Serpentine trail to the lookout. 30 min up.",
              category: "activity",
              location: "Parc du Mont-Royal",
              isChecked: false,
              sortOrder: 3,
            },
            {
              id: "item-5",
              time: "7:00 PM",
              title: "Dinner at Joe Beef",
              description: "Reservations booked. Try the lobster spaghetti.",
              category: "food",
              location: "2491 Rue Notre-Dame O",
              link: "https://www.joebeef.ca",
              cost: "$80/person",
              isChecked: false,
              sortOrder: 4,
            },
          ],
        },
        {
          id: "day-2",
          dayNumber: 2,
          date: "2026-07-11",
          items: [
            {
              id: "item-6",
              time: "9:30 AM",
              title: "Bagels at St-Viateur",
              description: "Sesame > everything. Get a dozen to go.",
              category: "food",
              location: "263 Rue Saint-Viateur O",
              cost: "$12/dozen",
              isChecked: false,
              sortOrder: 0,
            },
            {
              id: "item-7",
              time: "11:00 AM",
              title: "Jean-Talon Market",
              description: "Browse fresh produce, cheese, and pastries",
              category: "activity",
              location: "7070 Av. Henri-Julien",
              isChecked: false,
              sortOrder: 1,
            },
            {
              id: "item-8",
              time: "2:00 PM",
              title: "Montreal Museum of Fine Arts",
              category: "activity",
              location: "1380 Rue Sherbrooke O",
              cost: "$24",
              link: "https://www.mbam.qc.ca",
              isChecked: false,
              sortOrder: 2,
            },
            {
              id: "item-9",
              time: "6:00 PM",
              title: "Mile End food crawl",
              description: "Fairmount Bagels → Wilensky's → Dieu du Ciel!",
              category: "food",
              location: "Mile End",
              cost: "$40",
              isChecked: false,
              sortOrder: 3,
            },
          ],
        },
        {
          id: "day-3",
          dayNumber: 3,
          date: "2026-07-12",
          items: [
            {
              id: "item-10",
              time: "10:00 AM",
              title: "Biking the Lachine Canal",
              description: "Rent BIXI bikes, ride from Old Port to Atwater Market",
              category: "activity",
              location: "Lachine Canal",
              cost: "$8/hr",
              isChecked: false,
              sortOrder: 0,
            },
            {
              id: "item-11",
              time: "12:30 PM",
              title: "Lunch at Atwater Market",
              category: "food",
              location: "138 Av. Atwater",
              isChecked: false,
              sortOrder: 1,
            },
            {
              id: "item-12",
              time: "3:00 PM",
              title: "Plateau-Mont-Royal walk",
              description: "Colourful row houses, street art, boutiques",
              category: "activity",
              location: "Le Plateau-Mont-Royal",
              isChecked: false,
              sortOrder: 2,
            },
          ],
        },
      ],
      foodSpots: [
        { id: "food-1", name: "Schwartz's Deli", type: "restaurant", notes: "Legendary smoked meat. Cash only. Line moves fast.", link: "https://www.schwartzsdeli.com", priceRange: "$10-20", sortOrder: 0 },
        { id: "food-2", name: "Joe Beef", type: "restaurant", notes: "Book 2 weeks ahead. Lobster spaghetti is a must.", link: "https://www.joebeef.ca", priceRange: "$60-100", sortOrder: 1 },
        { id: "food-3", name: "St-Viateur Bagel", type: "bakery", notes: "Sesame bagels, wood-fired 24/7", priceRange: "$1-2", sortOrder: 2 },
        { id: "food-4", name: "Dieu du Ciel!", type: "bar", notes: "Craft beer. Try the Péché Mortel stout.", priceRange: "$8-12", sortOrder: 3 },
        { id: "food-5", name: "Wilensky's Light Lunch", type: "restaurant", notes: "The Special: salami + bologna on a pressed roll", priceRange: "$5-10", sortOrder: 4 },
        { id: "food-6", name: "Olive et Gourmando", type: "cafe", notes: "Great brunch spot in Old Montreal. Go early.", priceRange: "$15-25", sortOrder: 5 },
      ],
      activities: [
        { id: "act-1", name: "Notre-Dame Basilica", notes: "Stunning interior. AURA light show at night.", cost: "$18", location: "110 Rue Notre-Dame O", link: "https://www.basiliquenotredame.ca", sortOrder: 0 },
        { id: "act-2", name: "Mount Royal Lookout", notes: "Best city panorama. 30 min hike.", location: "Parc du Mont-Royal", sortOrder: 1 },
        { id: "act-3", name: "Jean-Talon Market", notes: "Farmers market, local cheeses and pastries", location: "7070 Av. Henri-Julien", sortOrder: 2 },
        { id: "act-4", name: "Lachine Canal Biking", notes: "10km path, BIXI bikes available", cost: "$8/hr", location: "Lachine Canal", sortOrder: 3 },
      ],
    },
    {
      id: "dest-2",
      name: "Quebec City",
      duration: "3 nights",
      hotel: {
        name: "Fairmont Le Château Frontenac",
        address: "1 Rue des Carrières, Québec",
        link: "https://www.fairmont.com/frontenac-quebec",
      },
      sortOrder: 1,
      days: [
        {
          id: "day-4",
          dayNumber: 1,
          date: "2026-07-14",
          items: [
            {
              id: "item-20",
              time: "10:00 AM",
              title: "Drive to Quebec City",
              description: "3hr drive from Montreal via A-20",
              category: "transport",
              cost: "$40 gas",
              isChecked: false,
              sortOrder: 0,
            },
            {
              id: "item-21",
              time: "2:00 PM",
              title: "Check in at Château Frontenac",
              category: "accommodation",
              location: "1 Rue des Carrières",
              isChecked: false,
              sortOrder: 1,
            },
            {
              id: "item-22",
              time: "3:30 PM",
              title: "Walk Terrasse Dufferin & Plains of Abraham",
              category: "activity",
              location: "Old Quebec",
              isChecked: false,
              sortOrder: 2,
            },
            {
              id: "item-23",
              time: "7:00 PM",
              title: "Dinner at Chez Muffy",
              description: "Farm-to-table in an old warehouse",
              category: "food",
              location: "10 Rue Saint-Antoine",
              cost: "$65/person",
              isChecked: false,
              sortOrder: 3,
            },
          ],
        },
        {
          id: "day-5",
          dayNumber: 2,
          date: "2026-07-15",
          items: [
            {
              id: "item-24",
              time: "9:00 AM",
              title: "Petit Champlain stroll & breakfast",
              description: "North America's oldest commercial street",
              category: "activity",
              location: "Quartier Petit Champlain",
              isChecked: false,
              sortOrder: 0,
            },
            {
              id: "item-25",
              time: "11:00 AM",
              title: "Montmorency Falls",
              description: "30m higher than Niagara. Walk across the suspension bridge.",
              category: "activity",
              location: "Parc de la Chute-Montmorency",
              cost: "$6 parking",
              link: "https://www.sepaq.com/ct/pcm",
              isChecked: false,
              sortOrder: 1,
            },
            {
              id: "item-26",
              time: "2:00 PM",
              title: "Île d'Orléans drive",
              description: "Farm island loop. Stop for strawberries, chocolate, cider.",
              category: "activity",
              location: "Île d'Orléans",
              isChecked: false,
              sortOrder: 2,
            },
          ],
        },
      ],
      foodSpots: [
        { id: "food-10", name: "Chez Muffy", type: "restaurant", notes: "Farm-to-table in Auberge Saint-Antoine", priceRange: "$50-80", sortOrder: 0 },
        { id: "food-11", name: "Le Croquembouche", type: "bakery", notes: "Best croissants in QC", priceRange: "$5-10", sortOrder: 1 },
        { id: "food-12", name: "Paillard", type: "cafe", notes: "Huge sandwiches and pastries, fast casual", priceRange: "$10-18", sortOrder: 2 },
      ],
      activities: [
        { id: "act-10", name: "Château Frontenac", notes: "Even if not staying, explore the lobby & terrace", location: "1 Rue des Carrières", sortOrder: 0 },
        { id: "act-11", name: "Montmorency Falls", notes: "Taller than Niagara. Suspension bridge & cable car.", cost: "$6", location: "Parc de la Chute-Montmorency", sortOrder: 1 },
        { id: "act-12", name: "Île d'Orléans", notes: "Scenic drive, farm stops, chocolate shops", location: "Île d'Orléans", sortOrder: 2 },
      ],
    },
  ],
};
